### ISSUE TITLE
WildInspect does not work on Paper 1.17.1

### ISSUE THREAD

**Issue by vdl19** [BG-Software-LLC/WildInspect#15]
### Minecraft's Version

Paper 1.17.1 #296

### Plugin's Version

WildInspect-2.3.3 + WildInspect-b17 + WildInspect-b16 + WildInspect-b15

### Describe the bug

If I click with the right or left button I have no information about the blocks and in the server console I have messages like below :
.............................................
WildInspect-2.3.3

>.... [17:59:20 WARN]: [WildInspect] Plugin WildInspect v2.3.3 generated an exception while executing task 9107
java.lang.NoSuchMethodError: 'java.lang.String net.coreprotect.database.lookup.BlockLookup.results(java.lang.String, java.sql.Statement, org.bukkit.block.BlockState, org.bukkit.command.CommandSender, int, int, int)'
at com.bgsoftware.wildinspect.coreprotect.CoreProtectHook.performBlockLookup(CoreProtectHook.java:49) ~[WildInspect-2.3.3.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.getMaxPage(CoreProtect.java:161) ~[WildInspect-2.3.3.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:77) ~[WildInspect-2.3.3.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-296]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-296]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-296]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
>.... [17:59:22 WARN]: [WildInspect] Plugin WildInspect v2.3.3 generated an exception while executing task 9162
java.lang.NoSuchMethodError: 'java.lang.String net.coreprotect.database.Lookup.interactionLookup(java.lang.String, java.sql.Statement, org.bukkit.block.Block, org.bukkit.command.CommandSender, int, int, int)'
at com.bgsoftware.wildinspect.coreprotect.CoreProtectHook.performInteractLookup(CoreProtectHook.java:41) ~[WildInspect-2.3.3.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.getMaxPage(CoreProtect.java:158) ~[WildInspect-2.3.3.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:77) ~[WildInspect-2.3.3.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-296]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-296]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-296]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) ~[?:?]

.............................................
WildInspect-b17 :

>.... [17:46:05 WARN]: [WildInspect] Plugin WildInspect v2.3.3-DEVb17 generated an exception while executing task 9076
java.lang.NoSuchMethodError: 'java.lang.String net.coreprotect.database.lookup.BlockLookup.results(java.lang.String, java.sql.Statement, org.bukkit.block.BlockState, org.bukkit.command.CommandSender, int, int, int)'
at com.bgsoftware.wildinspect.coreprotect.CoreProtectHook.performBlockLookup(CoreProtectHook.java:49) ~[WildInspect-b17.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.getMaxPage(CoreProtect.java:163) ~[WildInspect-b17.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:79) ~[WildInspect-b17.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-296]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-296]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-296]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) ~[?:?]

.............................................
WildInspect-b16 :

>.... [17:42:32 WARN]: [WildInspect] Plugin WildInspect v2.3.3-DEVb16 generated an exception while executing task 10114
java.lang.NoSuchMethodError: 'java.lang.String net.coreprotect.database.Lookup.interactionLookup(java.lang.String, java.sql.Statement, org.bukkit.block.Block, org.bukkit.command.CommandSender, int, int, int)'
at com.bgsoftware.wildinspect.coreprotect.CoreProtectHook.performInteractLookup(CoreProtectHook.java:41) ~[WildInspect-b16.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.getMaxPage(CoreProtect.java:160) ~[WildInspect-b16.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:79) ~[WildInspect-b16.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-296]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-296]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-296]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) ~[?:?]

.............................................
WildInspect-b15 :

>.... [17:51:09 WARN]: [WildInspect] Plugin WildInspect v2.3.3-DEVb15 generated an exception while executing task 17055
java.lang.NoSuchMethodError: 'java.lang.String net.coreprotect.database.lookup.BlockLookup.results(java.lang.String, java.sql.Statement, org.bukkit.block.BlockState, org.bukkit.command.CommandSender, int, int, int)'
at com.bgsoftware.wildinspect.coreprotect.CoreProtectHook.performBlockLookup(CoreProtectHook.java:49) ~[WildInspect-b15.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.getMaxPage(CoreProtect.java:163) ~[WildInspect-b15.jar:?]
at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:79) ~[WildInspect-b15.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-296]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-296]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-296]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) ~[?:?]

### To Reproduce

Just set up one of the vesion I named and click

**Comment by OmerBenGera** [comment]
This is due to your CoreProtect version.
which version do you use?

**Comment by vdl19** [comment]
The latest version:     CoreProtect-20.1

**Comment by vdl19** [comment]
With /co status :

>....=>.... [13:00:04 INFO]: ----- CoreProtect -----
>.... [13:00:04 INFO]: Version: CoreProtect v20.1.
>.... [13:00:04 INFO]: License: Invalid donation key. (Please check config.yml)
>.... [13:00:04 INFO]: Database: Using SQLite. (Initial DB: 19.0)
>.... [13:00:04 INFO]: WorldEdit: Integration enabled.
>.... [13:00:04 INFO]: Consumer: 0 items in queue.
>.... [13:00:04 INFO]: Discord: www.coreprotect.net/discord/
>.... [13:00:04 INFO]: Patreon: www.patreon.com/coreprotect/

**Comment by OmerBenGera** [comment]
I will look into that once I am back home.

**Comment by vdl19** [comment]
ok thanks

**Comment by vdl19** [comment]
I just tested the last build, it does not give me any info or with the right or left click. I join you what is displayed in the console of my server when I left click then right click on a block

[finspect.txt](https://github.com/BG-Software-LLC/WildInspect/files/7354549/finspect.txt)

I don't have enough time now to do more tests by removing almost all plugins.
For the faction plugin I use "SaberFactions 2.9.6-RC"
